### ISSUE TITLE
我是用了，只显示一下就再也不显示了

### ISSUE THREAD

**Issue by fridayyue** [Liaoworking/GHConsole#2]
在项目中使用了，显示了一下就就再也不显示，找不到了。

**Comment by Liaoworking** [comment]
大兄弟，你说的那个bug我已经修复，可能是因为添加到keyWindow的时候keyWindow还没有生成。现已经解决。 十分感谢你的反馈。

**Comment by fridayyue** [comment]
emmm还有一个建议每次打印的时候都bringSubviewToFront，这样一些自定义window上的view不会覆盖住

**Comment by Liaoworking** [comment]
好的  谢谢你的建议。这个我今天修改后检测一下就再发一版上来。thanks.
