### ISSUE TITLE
iOS 8系统上状态栏不显示

### ISSUE THREAD

**Issue by SCFighting** [Liaoworking/GHConsole#6]

**Comment by Liaoworking** [comment]
谢谢你提的issue, 这个是由于在iOS8上创建了一个新的window ，keywindow的层级大于statusBar的层级，就遮挡住的statusBar。等测试完成后会提交一个新的版本。再次感谢。

**Comment by Liaoworking** [comment]
解决方案：在项目的Info.plist 文件中 添加一行属性配置
View controller-based status bar appearance ＝NO   thanks.

**Comment by SCFighting** [comment]
好的，谢谢

发自我的 iPhone
